// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ TB__DOT__clk;
        CData/*0:0*/ TB__DOT__rst;
        CData/*0:0*/ TB__DOT__usePredictor;
        CData/*2:0*/ TB__DOT__dmemSize;
        CData/*0:0*/ TB__DOT__dmemWen;
        CData/*0:0*/ TB__DOT__dmemWenFinal;
        CData/*0:0*/ TB__DOT__uartWen;
        CData/*7:0*/ TB__DOT__uartData;
        CData/*0:0*/ TB__DOT__uut__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__usePredictor;
        CData/*2:0*/ TB__DOT__uut__DOT__dmemSize;
        CData/*0:0*/ TB__DOT__uut__DOT__dmemWen;
        CData/*0:0*/ TB__DOT__uut__DOT__P_bPredictTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__E_wrongBranch;
        CData/*0:0*/ TB__DOT__uut__DOT__F_bPredictedTaken;
        CData/*4:0*/ TB__DOT__uut__DOT__D_rdAddr;
        CData/*4:0*/ TB__DOT__uut__DOT__D_r1Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__D_r2Addr;
        CData/*0:0*/ TB__DOT__uut__DOT__D_bPredictedTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__D_regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__D_branch;
        CData/*0:0*/ TB__DOT__uut__DOT__D_jump;
        CData/*0:0*/ TB__DOT__uut__DOT__D_memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__D_useF7;
        CData/*0:0*/ TB__DOT__uut__DOT__D_useRegAdd;
        CData/*0:0*/ TB__DOT__uut__DOT__D_funct7_6;
        CData/*2:0*/ TB__DOT__uut__DOT__D_funct3;
        CData/*1:0*/ TB__DOT__uut__DOT__D_aluSrcA;
        CData/*1:0*/ TB__DOT__uut__DOT__D_regSrc;
        CData/*0:0*/ TB__DOT__uut__DOT__D_csrOp;
        CData/*0:0*/ TB__DOT__uut__DOT__D_aluSrcB;
        CData/*0:0*/ TB__DOT__uut__DOT__E_controlXfer;
        CData/*0:0*/ TB__DOT__uut__DOT__E_validInst;
        CData/*4:0*/ TB__DOT__uut__DOT__E_rdAddr;
        CData/*2:0*/ TB__DOT__uut__DOT__E_loadStoreSize;
        CData/*0:0*/ TB__DOT__uut__DOT__E_regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__E_memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__E_csrWrite;
        CData/*1:0*/ TB__DOT__uut__DOT__E_regSrc;
        CData/*4:0*/ TB__DOT__uut__DOT__E_r1Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__E_r2Addr;
        CData/*0:0*/ TB__DOT__uut__DOT__E_btbUpdate;
        CData/*0:0*/ TB__DOT__uut__DOT__E_pcSel;
        CData/*0:0*/ TB__DOT__uut__DOT__E_branch;
        CData/*4:0*/ TB__DOT__uut__DOT__M_rdAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__M_regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__M_csrWrite;
        CData/*1:0*/ TB__DOT__uut__DOT__M_regSrc;
        CData/*2:0*/ TB__DOT__uut__DOT__M_dmemSize;
        CData/*0:0*/ TB__DOT__uut__DOT__M_dmemWen;
        CData/*4:0*/ TB__DOT__uut__DOT__W_rdAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__W_regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__W_csrWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__H_stallF;
        CData/*1:0*/ TB__DOT__uut__DOT__H_fwdAE;
        CData/*1:0*/ TB__DOT__uut__DOT__H_fwdBE;
        CData/*0:0*/ TB__DOT__uut__DOT__H_flushE;
        CData/*0:0*/ TB__DOT__uut__DOT__H_flushD;
        CData/*0:0*/ TB__DOT__uut__DOT__H_stallD;
        CData/*1:0*/ TB__DOT__uut__DOT__hazard__DOT__fwdAE;
        CData/*1:0*/ TB__DOT__uut__DOT__hazard__DOT__fwdBE;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__flushE;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__flushD;
    };
    struct {
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__stallD;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__stallF;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__r1AddrE;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__r2AddrE;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__r1AddrD;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__r2AddrD;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__rdM;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__rdE;
        CData/*4:0*/ TB__DOT__uut__DOT__hazard__DOT__rdW;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__regWriteM;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__regWriteW;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__regSrcE0;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__wrongBranchE;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__r1EqMem;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__r2EqMem;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__r1EqW;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__r2EqW;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__lwStall;
        CData/*0:0*/ TB__DOT__uut__DOT__hazard__DOT__bStall;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__bPredictTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__usePredictor;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__pcSelE;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__wrongBranchE;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__stall;
        CData/*0:0*/ TB__DOT__uut__DOT__fetch__DOT__bPredictedTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__stall;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__flush;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrWriteW;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__wrongBranch;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__controlXfer;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__validInst;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__bPredictedTakenF;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__rdAddrW;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__regWriteW;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__rdAddr;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__r1Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__r2Addr;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__bPredictedTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__branch;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__jump;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__useF7;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__useRegAdd;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__funct7_6;
        CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__funct3;
        CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__aluSrcA;
        CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__regSrc;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrOp;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__aluSrcB;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__bPredictedTakenSv;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__op;
        CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__immCntrl;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__op;
        CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__funct3;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__branch;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__jump;
        CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__immCntrl;
    };
    struct {
        CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__aluSrcA;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__useF7;
        CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__regSrc;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__useRegAdd;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__aluSrcB;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__csrOp;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__shift;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__wrongOpcode;
        CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__immCntrl;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__addr1;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__addr2;
        CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__writeAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__writeEn;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__negClk;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__wEn;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__wrongBranch;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__validInst;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__controlXfer;
        CData/*3:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__readAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__flush;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrOpD;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__fwdA;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__fwdB;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__bPredictedTakenD;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__rdAddrD;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r1AddrD;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r2AddrD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__regWriteD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__memWriteD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__branchD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__jumpD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useF7D;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useRegAddD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__funct7_6D;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__funct3D;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcAD;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__regSrcD;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcBD;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__loadStoreSize;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r1Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r2Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__rdAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrWrite;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__regSrc;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__btbUpdate;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__wrongBranch;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__pcSel;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__branch;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__controlXfer;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__validInst;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__bPredictedTakenSv;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__rdAddrSv;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r1AddrSv;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__r2AddrSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__regWriteSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__memWriteSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__branchSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__jumpSv;
    };
    struct {
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useF7Sv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useRegAddSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__funct7_6Sv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrOpSv;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__funct3Sv;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcASv;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__regSrcSv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcBSv;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__funct3;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcA;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__jump;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__funct7_6;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__branchFlag;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__isJalr;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useRegAdd;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__bPredictedTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__useF7;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrRead;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__aluSrcB;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__funct3;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__funct7_6;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__branch;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__csrOp;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__useF7;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__useRegAdd;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__branchFlag;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__zero;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__inv;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__f7;
        CData/*2:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__aluCntrl;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__srcBlwr;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__r1Addr;
        CData/*4:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__rdAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrOp;
        CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__funct3;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrRead;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrReadIn;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrWriteIn;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__nrdIs0;
        CData/*0:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__nrIs0;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__rst;
        CData/*1:0*/ TB__DOT__uut__DOT__mem__DOT__regSrcE;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__regWriteE;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__memWriteE;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__csrWriteE;
        CData/*4:0*/ TB__DOT__uut__DOT__mem__DOT__rdAddrE;
        CData/*2:0*/ TB__DOT__uut__DOT__mem__DOT__loadStoreSizeE;
        CData/*4:0*/ TB__DOT__uut__DOT__mem__DOT__rdAddr;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__csrWrite;
        CData/*1:0*/ TB__DOT__uut__DOT__mem__DOT__regSrc;
        CData/*2:0*/ TB__DOT__uut__DOT__mem__DOT__dmemSize;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__dmemWen;
        CData/*4:0*/ TB__DOT__uut__DOT__mem__DOT__rdAddrSv;
        CData/*2:0*/ TB__DOT__uut__DOT__mem__DOT__loadStoreSizeSv;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__regWriteSv;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__csrWriteSv;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__memWriteSv;
        CData/*1:0*/ TB__DOT__uut__DOT__mem__DOT__regSrcSv;
        CData/*0:0*/ TB__DOT__uut__DOT__mem__DOT__memWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__rst;
    };
    struct {
        CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__regSrcM;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__regWriteM;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__csrWriteM;
        CData/*4:0*/ TB__DOT__uut__DOT__wback__DOT__rdAddrM;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__regWrite;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__csrWrite;
        CData/*4:0*/ TB__DOT__uut__DOT__wback__DOT__rdAddr;
        CData/*4:0*/ TB__DOT__uut__DOT__wback__DOT__rdAddrSv;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__regWriteSv;
        CData/*0:0*/ TB__DOT__uut__DOT__wback__DOT__csrWriteSv;
        CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__regSrcSv;
        CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__regSrc;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchHit;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__exTaken;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__exBranch;
        CData/*5:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchIndex;
        CData/*5:0*/ TB__DOT__uut__DOT__bPredict__DOT__exIndex;
        CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchCounter;
        CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__exCounter;
        CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__count;
        CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__nextCount;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__exHit;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_req_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_req_ready;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_pred_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_pred_taken;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_train_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_train_ready;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_train_taken;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__req_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__req_ready;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__pred_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__pred_taken;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_taken;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_ready;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__req_idx;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_idx;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__rd_en;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__rd_idx;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__rd_v;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__wr_en;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__wr_idx;
        CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__state;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__wrong;
        CData/*7:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT____Vlvbound_hc0686a0f__0;
        CData/*7:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT____Vlvbound_hc0686a0f__1;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__clk;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__rst;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__rd_en;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__rd_idx;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__rd_valid;
        CData/*0:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__wr_en;
        CData/*6:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__wr_idx;
        CData/*0:0*/ TB__DOT__instr__DOT__clk;
        CData/*2:0*/ TB__DOT__data__DOT__size;
        CData/*0:0*/ TB__DOT__data__DOT__clk;
        CData/*0:0*/ TB__DOT__data__DOT__wEn;
        CData/*0:0*/ TB__DOT__uart__DOT__clk;
        CData/*0:0*/ TB__DOT__uart__DOT__rst;
    };
    struct {
        CData/*0:0*/ TB__DOT__uart__DOT__wEn;
        CData/*7:0*/ TB__DOT__uart__DOT__data;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__fetch__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__decode__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__decode__DOT__regF__DOT__negClk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__decode__DOT__csrF__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__execute__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__mem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__wback__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__bPredict__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__data__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__TB__DOT__uart__DOT__clk__0;
        SData/*11:0*/ TB__DOT__uut__DOT__D_csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__E_csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__M_csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__W_csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__decode__DOT__csrAddrW;
        SData/*11:0*/ TB__DOT__uut__DOT__decode__DOT__csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__wAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__execute__DOT__csrAddrD;
        SData/*11:0*/ TB__DOT__uut__DOT__execute__DOT__csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__execute__DOT__csrAddrSv;
        SData/*11:0*/ TB__DOT__uut__DOT__mem__DOT__csrAddrE;
        SData/*11:0*/ TB__DOT__uut__DOT__mem__DOT__csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__mem__DOT__csrAddrSv;
        SData/*11:0*/ TB__DOT__uut__DOT__wback__DOT__csrAddrM;
        SData/*11:0*/ TB__DOT__uut__DOT__wback__DOT__csrAddr;
        SData/*11:0*/ TB__DOT__uut__DOT__wback__DOT__csrAddrSv;
        IData/*31:0*/ TB__DOT__imemRdata;
        IData/*31:0*/ TB__DOT__imemAddr;
        IData/*31:0*/ TB__DOT__dmemRdata;
        IData/*31:0*/ TB__DOT__dmemRdataFinal;
        IData/*31:0*/ TB__DOT__dmemWdata;
        IData/*31:0*/ TB__DOT__dmemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__imemRdata;
        IData/*31:0*/ TB__DOT__uut__DOT__imemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__dmemRdata;
        IData/*31:0*/ TB__DOT__uut__DOT__dmemWdata;
        IData/*31:0*/ TB__DOT__uut__DOT__dmemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__P_btbTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__E_pcTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__F_instr;
        IData/*31:0*/ TB__DOT__uut__DOT__F_pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__F_pc;
        IData/*31:0*/ TB__DOT__uut__DOT__D_pc;
        IData/*31:0*/ TB__DOT__uut__DOT__D_pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__D_a;
        IData/*31:0*/ TB__DOT__uut__DOT__D_b;
        IData/*31:0*/ TB__DOT__uut__DOT__D_immExt;
        IData/*31:0*/ TB__DOT__uut__DOT__E_aluResult;
        IData/*31:0*/ TB__DOT__uut__DOT__E_writeData;
        IData/*31:0*/ TB__DOT__uut__DOT__E_pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__E_pc;
        IData/*31:0*/ TB__DOT__uut__DOT__E_csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__E_btbTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__M_pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__M_aluResult;
        IData/*31:0*/ TB__DOT__uut__DOT__M_readData;
        IData/*31:0*/ TB__DOT__uut__DOT__M_csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__M_dmemWdata;
    };
    struct {
        IData/*31:0*/ TB__DOT__uut__DOT__M_dmemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__M_dmemRdata;
        IData/*31:0*/ TB__DOT__uut__DOT__W_rd;
        IData/*31:0*/ TB__DOT__uut__DOT__W_csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__btbTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__pcTargetE;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__imemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__imemData;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__instr;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__pc;
        IData/*31:0*/ TB__DOT__uut__DOT__fetch__DOT__pc_;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__csrResultW;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__instrF;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pcF;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pcPlus4F;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__rdW;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pc;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__a;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__b;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__immExt;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__instrSv;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pcSv;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__pcPlus4Sv;
        IData/*24:0*/ TB__DOT__uut__DOT__decode__DOT__immSrc;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__zimm;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__r2;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__r1;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__csr;
        IData/*24:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__immSrc;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__immExt;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__reg1;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__reg2;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__regF__DOT__writeData;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__csr;
        IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__wData;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__aluResultM;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__resultW;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcD;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcPlus4D;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__aD;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__bD;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__immExtD;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__aluResult;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__writeData;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pc;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__btbTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcSv;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcPlus4Sv;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__aSv;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__bSv;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__immExtSv;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__a;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__b;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__r1Hz;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__r2Hz;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__srcA;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__srcB;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__pcPlusImm;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__immExt;
    };
    struct {
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__srcA;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__srcB;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__alu__DOT__aluResult;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csr;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__rs1Uimm;
        IData/*31:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__aluResultE;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__writeDataE;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__pcPlus4E;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__dmemRdata;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__csrResultE;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__pcPlus4;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__readData;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__aluResult;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__dmemWdata;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__dmemAddr;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__aluResultSv;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__writeDataSv;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__csrResultSv;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__pcPlus4Sv;
        IData/*31:0*/ TB__DOT__uut__DOT__mem__DOT__writeData;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__aluResultM;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__readDataM;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__pcPlus4M;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__csrResultM;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__regResult;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__csrResult;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__readDataSv;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__pcPlus4Sv;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__aluResultSv;
        IData/*31:0*/ TB__DOT__uut__DOT__wback__DOT__csrResultSv;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchPc;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchTarget;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__exPc;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__exTarget;
        IData/*25:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchTag;
        IData/*25:0*/ TB__DOT__uut__DOT__bPredict__DOT__exTag;
        IData/*25:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchTagBtb;
        IData/*25:0*/ TB__DOT__uut__DOT__bPredict__DOT__exTagBtb;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__ghr_local;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_pred_conf;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_train_pc;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_train_ghr;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__percep_req_ghr;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__req_pc;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__req_ghr;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__pred_conf;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_pc;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__train_ghr;
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__rd_data;
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__wr_data;
        IData/*27:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__ghr_latched;
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__packed_vec;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__accum;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__i;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__msb;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__tmpv;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__delta;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__t_signed;
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__unnamedblk1__DOT__newpack;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT____Vlvbound_hf5eb4660__0;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT____Vlvbound_hf5eb4660__1;
        IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT____Vlvbound_hf5eb4660__2;
    };
    struct {
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__rd_data;
        VlWide<8>/*231:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__wr_data;
        IData/*31:0*/ TB__DOT__instr__DOT__rData;
        IData/*31:0*/ TB__DOT__instr__DOT__rAddr;
        IData/*31:0*/ TB__DOT__data__DOT__wData;
        IData/*31:0*/ TB__DOT__data__DOT__rData;
        IData/*31:0*/ TB__DOT__data__DOT__addr;
        IData/*31:0*/ TB__DOT__data__DOT__addrplus1;
        IData/*31:0*/ TB__DOT__data__DOT__addrplus2;
        IData/*31:0*/ TB__DOT__data__DOT__addrplus3;
        IData/*31:0*/ TB__DOT__data__DOT__addrMinusOff;
        IData/*31:0*/ __VactIterCount;
        QData/*60:0*/ TB__DOT__uut__DOT__bPredict__DOT__fetchEntry;
        QData/*60:0*/ TB__DOT__uut__DOT__bPredict__DOT__exEntry_;
        QData/*60:0*/ TB__DOT__uut__DOT__bPredict__DOT__exEntryUpdated;
        VlUnpacked<IData/*31:0*/, 32> TB__DOT__uut__DOT__decode__DOT__regF__DOT__registers;
        VlUnpacked<IData/*31:0*/, 16> TB__DOT__uut__DOT__decode__DOT__csrF__DOT__csRegisters;
        VlUnpacked<QData/*60:0*/, 64> TB__DOT__uut__DOT__bPredict__DOT__btb_mem;
        VlUnpacked<IData/*31:0*/, 29> TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__weight_arr;
        VlUnpacked<VlWide<8>/*231:0*/, 128> TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__mem;
        VlUnpacked<IData/*31:0*/, 16383> TB__DOT__instr__DOT__mem;
        VlUnpacked<CData/*7:0*/, 32768> TB__DOT__data__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 29>, false, IData/*31:0*/, 1> __VdlyCommitQueueTB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__weight_arr;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__hazard__DOT__NO_FWD = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__hazard__DOT__MEM_FWD = 2U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__hazard__DOT__WB_FWD = 1U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_RTYPE = 0x0cU;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_IARTHTYPE = 4U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_LOADTYPE = 0U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_STYPE = 8U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_BTYPE = 0x18U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_AUIPC = 5U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_LUI = 0x0dU;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_JAL = 0x1bU;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_JALR = 0x19U;
    static constexpr CData/*4:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__OPCODE_CSR = 0x1cU;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_DEFAULT = 0U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_SHAMT = 1U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_I = 2U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_S = 3U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_B = 4U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_U = 5U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__IMM_TYPE_J = 6U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__ALU_SRC = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__MEM_SRC = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__PC_SRC = 2U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__RS1 = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__PC = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__decode__DOT__cntrlU__DOT__ZERO = 3U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_SHAMT = 1U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_I = 2U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_S = 3U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_B = 4U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_U = 5U;
    static constexpr CData/*2:0*/ TB__DOT__uut__DOT__decode__DOT__extImm__DOT__IMM_TYPE_J = 6U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__RS1 = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__PC = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__CSRRW = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__CSRRS = 2U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__execute__DOT__csrU__DOT__CSRRC = 3U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__ALU_SRC = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__MEM_SRC = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__wback__DOT__PC_SRC = 2U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__sTaken = 2U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__wTaken = 0U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__wNtaken = 1U;
    static constexpr CData/*1:0*/ TB__DOT__uut__DOT__bPredict__DOT__sNtaken = 3U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__decode__DOT__csrF__DOT__regSize = 0x00000010U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__BTB_ENTRIES = 0x00000040U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TARGET_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__COUNTER_WIDTH = 2U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__INDEX_WIDTH = 6U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TAG_WIDTH = 0x0000001aU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__VALID_BIT = 0U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__COUNTER_LSB = 1U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__COUNTER_MSB = 2U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TARGET_LSB = 3U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TARGET_MSB = 0x00000022U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TAG_LSB = 0x00000023U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__TAG_MSB = 0x0000003cU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__MEM_WIDTH = 0x0000003dU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__P_INDEX_BITS = 7U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__P_HIST = 0x0000001cU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__P_WBITS = 8U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__P_THRESH = 0x00000044U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__INDEX_BITS = 7U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__HIST = 0x0000001cU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__W_BITS = 8U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__THRESH = 0x00000044U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__TOTAL_W = 0x000000e8U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__INDEX_BITS = 7U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__HIST = 0x0000001cU;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__W_BITS = 8U;
    static constexpr IData/*31:0*/ TB__DOT__uut__DOT__bPredict__DOT__u_percep__DOT__mem__DOT__N = 0x00000080U;
    static constexpr IData/*31:0*/ TB__DOT__instr__DOT__DEPTH = 0x00003fffU;
    static constexpr IData/*31:0*/ TB__DOT__instr__DOT__ADDR_WIDTH = 0x0000000eU;
    static constexpr IData/*31:0*/ TB__DOT__data__DOT__DEPTH = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
